apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::657003531816:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-6VT7LMPCWEWZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::657003531816:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-30T10:40:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1801"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fcab324e-eebb-4798-a68a-b90e58e4922c
